### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Joe-Richard-666** [dazzle-me/Gaze-Estimation#1]
Hello, I want to ask how to download the dataset?

**Comment by dazzle-me** [comment]
XGaze dataset is presented by [AIT Lab](https://ait.ethz.ch/index.php), you can find more information on [XGaze](https://ait.ethz.ch/projects/2020/ETH-XGaze/) page.

On the bottom of the page you can find a link to [google doc](https://docs.google.com/forms/d/e/1FAIpQLScaGNYTVI7-h8ZHu9y_kQzhC1Ab4fo4fXtRDMNZ5y2wpLx3MA/viewform), where you can ask creators to give you the link to download the dataset.
